package fr.unice.polytech.elim9;

/**
 * Created by nathael on 29/12/16.
 */

enum StatType {
    CHARGING_TIME, CHARGING_PCT,
    ACTIVE_DISCHARGING_TIME, ACTIVE_DISCHARGING_PCT,
    INACTIVE_DISCHARGING_TIME, INACTIVE_DISCHARGING_PCT
}